feat : config infra for deploy on aws

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,6 +13,15 @@ build_images:
   services:
     - docker:24.0.5-dind
   before_script:
+    - |
+      if [ -z "$AWS_REGION" ] || [ -z "$AWS_ACCOUNT_ID" ]; then
+        echo "=========================================================================="
+        echo "ERROR: AWS_REGION hoặc AWS_ACCOUNT_ID chưa được định nghĩa trong GitLab CI/CD Variables!"
+        echo "LƯU Ý: Nếu bạn đang chạy trên nhánh feature (nhánh phụ), hãy đảm bảo rằng bạn đã"
+        echo "TẮT (UNCHECK) thuộc tính 'Protect variable' trong phần cấu hình biến của GitLab."
+        echo "=========================================================================="
+        exit 1
+      fi
     - apk add --no-cache aws-cli
     - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
   script:
